name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please provide detailed information to help us understand your needs.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I searched existing issues to avoid duplicates
          required: true
        - label: I checked the documentation to ensure this doesn't already exist
          required: true
        - label: This is a feature request, not a bug report or usage question
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "I need to... but currently I have to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution in detail
      placeholder: "I would like the ability to..."
    validations:
      required: true

  - type: textarea
    id: api-design
    attributes:
      label: API Design
      description: How would you like this feature to work? (code examples welcome)
      render: rust
      placeholder: |
        // Example of how you'd like to use this feature
        let client = OpenRouterClient::new()
            .with_new_feature(options)?;
        
        let result = client.new_method().await?;

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered?
      placeholder: "I considered... but it doesn't work because..."

  - type: checkboxes
    id: category
    attributes:
      label: Feature Category
      description: Check all that apply
      options:
        - label: New API endpoint support
        - label: Client configuration options
        - label: Authentication methods
        - label: Streaming enhancements
        - label: Error handling improvements
        - label: Type safety enhancements
        - label: MCP (Model Context Protocol) features
        - label: Performance optimizations
        - label: Developer experience
        - label: Documentation

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Blocking my use case
        - Critical - Cannot use library without this
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I'm willing to submit a PR for this feature
        - label: I can help with testing/feedback
        - label: I can help with documentation
        - label: I need someone else to implement this

  - type: textarea
    id: use-case
    attributes:
      label: Use Case Details
      description: Provide more context about how you plan to use this feature
      placeholder: |
        - What type of application are you building?
        - How would this feature fit into your workflow?
        - Are there specific requirements or constraints?

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: What would be the impact of this feature?
      placeholder: |
        - How many users might benefit?
        - Would this be a breaking change?
        - Any compatibility concerns?

  - type: input
    id: examples
    attributes:
      label: Examples from Other Libraries
      description: Links to similar features in other libraries or languages
      placeholder: "https://example.com/similar-feature"